### ISSUE TITLE
non funziona una fava

### ISSUE THREAD

**Issue by mrbubbaz** [OpenTerzoSettore/test#1]
alksjdh aslkdjhf zdslkjh xckjhzxc asasadsads
![schermata 2016-06-13 alle 22 05 56](https://cloud.githubusercontent.com/assets/1698485/18840754/f0e22018-840f-11e6-9c02-8125fa006ffc.png)

**Comment by Mara515** [comment]
dddddddddddd

**Comment by mrbubbaz** [comment]
ho risolto tutto!
